### PR TITLE
Columnize fixes

### PR DESCRIPTION
**Pull request by user578**
The fixes of columnize function.

### CODE REVIEW

**Comment by user578** [comment]
Some extra info.
I found out the table splitting work not properly sometimes.
For example: 227 = 77 + 77 +73
After fix: 227 = 76 + 76 +75

I also fixed unwanted second call of columnize function. For example when you save the page and load it from disk.

**Comment by def-** [comment]
Thanks.

**Comment by user578** [comment]
Ouch, there is an older version of jQuery on the server. I gonna fix the code.

**Comment by def-** [comment]
Can't we just update jquery?

**Comment by user578** [comment]
I think yes. There is jquery-2.1.3.min.js in the player-data directory, it should work.

**Comment by def-** [comment]
Updated, I hope everything still works.

**Pull request merged**
