### PR TITLE
Add flatpak package to other downloads

### PR DESCRIPTION
**Pull request by miguilimzero**

### CODE REVIEW

**Comment by edg-l** [comment]
Imho if we add these we should also add gentoo guru, and all other distros?

**Review by def- — CHANGES_REQUESTED** [review]
If you want Flatpak to be listed there, then keep it up to date please. It currently shows 15.4, a 2 year old version.

**Comment by heinrich5991** [comment]
> Imho if we add these we should also add gentoo guru, and all other distros?
> 
> http://gpo.zugaina.org/games-action/DDNet/Dep

Please do that in a separate PR.

**Comment by heinrich5991** [comment]
> If you want Flatpak to be listed there, then keep it up to date please. It currently shows 15.4, a 2 year old version.

Might be related to https://github.com/ddnet/ddnet/issues/7607. Is it maybe just an outdated version number, but an up-to-date version?

**Comment by miguilimzero** [comment]
The version is actually updated (https://github.com/flathub/tw.ddnet.ddnet/pull/49). But as stated by @heinrich5991, the displayed number is from appdata.xml file from ddnet official repository. 

I reiterate that this file can be moved from the official repository to the flathub one (and be updated every flathub release) if it's not being used anywhere else.

**Comment by def-** [comment]
Yes, do that please. Afterwards I'm ok with linking to flathub.

**Comment by miguilimzero** [comment]
@def- done!

**Review by def- — APPROVED** [review]

**Pull request merged**
