### PR TITLE
Add description of weapon specific shields to explain

### PR DESCRIPTION
**Pull request by Zwelf**
Reopen of #188

### CODE REVIEW

**Comment by def-** [comment]
I have to move them: https://github.com/ddnet/ddnet/issues/5047

**Comment by def-** [comment]
@Zwelf planning to finish this? They have been released already

**Comment by Zwelf** [comment]
Thanks for notifying. I didn't see that it could finished. Will take a look to finish it now.

**Comment by Zwelf** [comment]
The weapon specific shield don't seem to have moved on the game/entity layer. So is mergeable as-is.

**Pull request merged**
