### PR TITLE
Original tee size is 96x96

### PR DESCRIPTION
**Pull request by ChillerDragon**
I don't think it changes something but it looks better c:

### CODE REVIEW

**Comment by def-** [comment]
Example?

**Comment by ChillerDragon** [comment]
template

I got the information from this template. Anyways i think the tee x and y are same and not different.
But as i said i don't think it actually changes something at least i didn't see it while testing. But i wonder where you got that 64 from.

**Comment by def-** [comment]
It makes the used space larger, thus the skin database would look emptier. Otherwise I don't see any effect of this.
screenshot-20181002 094207

**Comment by ChillerDragon** [comment]
@def- i guess you have to update some other values as well because the tee doesn't look original sized. I compared it against the TeeAssembler by Alexander and his version looked a bit bigger and better.
To see TeeAssembler in action you can checkout http://149.202.127.134/DDNetPP-web/players.php?players=10&page=0

Or a cleaner version here.
[TeeAssembler.zip](https://github.com/ddnet/ddnet-web/files/2436924/TeeAssembler.zip)

Compared to that one the tee.js one looks a bit small and maybe even lower resolution.

**Comment by def-** [comment]
Yeah, tee.js scales them down a notch, still looks good to me. If you want to, make a PR adding TeeAssembler and show us the differences in the Skin DB. If it's arguably better and about as fast, I'd add it.

**Comment by ChillerDragon** [comment]
Uhm i don't know if the TeeAssembler is better. It is different because it uses CSS and no javascript.
I used a very ugly way for my page to implement it i won't pull request that on to the nice ddnet codebase.

Oh and Alexander also mentioned something about the wrong order of body shadow but i am not sure about that one. I would prefer reworking the tee.js a bit but i am not sure if i am the right person for that yet.

**Comment by def-** [comment]
> I would prefer reworking the tee.js a bit but i am not sure if i am the right person for that yet.

Jump ahead and learn new skills. No one was born "the right person", you have to become him through effort and experience.

**Pull request closed without merging**
