### PR TITLE
New skin database

### PR DESCRIPTION
**Pull request by Jupeyy**
Small overview:
- Community skin type
- template skin type
- HD skins for all types
- json for skinlist(so it can in future be parsed by the client)
- skin database uses more javascript now
- skin downloads are onfly => less scripting on server side & search string can be used to download only searched files

We should defs make a backup of the old one.

To convert the old to the new few steps are required:
(small note, make sure the permissions are correct, old skin database used .sh scripts, now everything is one php script)
- mirror all current skins to the new directories: 
in www/html/skins/skin (better check this, never tested it):
```bash
mkdir -p community/uhd
mkdir -p template/uhd
mkdir uhd

cp *.png community
cp *.png community/uhd
cp *.png uhd
```

convert the current data.txt to skins.json, which should be put into www/html/skins/skin:
```html
<html>
<script>
function GO() {
	var File = document.getElementById("txtfile").files[0];
	File.text().then((val) => {
		var FileOut = document.getElementById("textout");
		var Lines = val.split("\n");
		var Out = "{ \"skins\": [";
		for(Line of Lines) {
		var LinePart = Line.split("/");
		if(LinePart.length != 4)
		continue;
		Out += "{ \"name\": \"" + LinePart[0] + "\", \"type\": \"normal\", \"hd\": { \"uhd\": false }," +
		"\"creator\": \"" + LinePart[1] + "\", \"license\": \"unknown\", \"bodypart\": \"full\", " +
		"\"gameversion\": \"tw-0.6\", \"date\": \"" + LinePart[3] + "\", \"skinpack\": " +
		"\"" + LinePart[2] + "\", \"imgtype\": \"png\" },";
		}
		if(Out.endsWith(","))
			Out = Out.substring(0, Out.length - 1);
		Out += "], \"version\": \"1.0.0\"}";

		FileOut.innerHTML = Out;
	});

}
</script>
<input type="file" id="txtfile">
<input type="button" value="GO" onclick="GO()">
<br>
<textarea id="textout" style="width:400px; height:500px;"></textarea>
</html>
```
Manually create skins.json, i suck at writing scripts xd

Also if you dislike design choices, create another PR after this, I'm not a designer, I just wanted to get this feature done finally

### CODE REVIEW

**Comment by def-** [comment]
screenshot-20220612@112942
- Adding a skin still shows the other text in front
- Going out of edit mode doesn't remove the add skin popup
- No website design around it?
- Edit mode doesn't require logging in now, had an htpasswd file on edit

**Comment by Jupeyy** [comment]
"Edit mode doesn't require logging in now, had an htpasswd file on edit" it still redirects to there, so doesnt matter i guess, its not intendet for normal users anyway.
No idea why the design is broken for you, for me it looks like normal ddnet site

**Comment by Jupeyy** [comment]
image

**Comment by Jupeyy** [comment]
> "Edit mode doesn't require logging in now, had an htpasswd file on edit" it still redirects to there, so doesnt matter i guess, its not intendet for normal users anyway. No idea why the design is broken for you, for me it looks like normal ddnet site

the edit before was lots of code duplication (it basically completly mirrored the whole normal page), so i prefer it this way

**Comment by Jupeyy** [comment]
Firefox doesn't support backdrop-filters, this browser is really so far behind webkit :/

**Comment by Jupeyy** [comment]
> * Going out of edit mode doesn't remove the add skin popup
fixed this

**Comment by Jupeyy** [comment]
> screenshot-20220612@112942
> 

image

isnt that jekyll syntax? i dont get why its there, but i also dont really know this tool.
Maybe it ate the newline somehow?
my editor uses LF line break, does it require CRLF?

**Comment by Learath2** [comment]
> Firefox doesn't support backdrop-filters, this browser is really so far behind webkit :/

Webkit doesn't support font-size-adjust and CSS subgrids, this renderer is so far behind Firefox.

**Comment by Jupeyy** [comment]
if webkit doesnt support it, it's probably useless >D

**Comment by def-** [comment]
Cool, seems to work. Running now: https://ddnet.tw/skins/

**Comment by def-** [comment]
Thanks a lot for the cleanup!

**Comment by C0D3D3V** [comment]
And how is this moderated? Can everyone go in edit mode and add skins?

**Comment by Jupeyy** [comment]
well everyone can open the mode now, but the actual edit is still behind a password, and i think thats also better..

but louis, ravie etc can less the restrictions for community tab

**Pull request merged**
