### PR TITLE
Add self contained explain layers in docs/explain-layers

### PR DESCRIPTION
**Pull request by Zwelf**
These svgs where originally created for the ddnet-wiki.gitlab.io
website. They are easy to update and modify:

* No external javascript dependencies: While the script uses javascript
  to display the explanation text, it doesn't need to load jquery
* png-graphics are embedded into the svg: this makes distributing the
  svg easier, since downloading/copying the file is enough
* easily updateable: running

  ```
  ./update_explain_layers.py --ddnet path/to/ddnet-repository
  ```

  is enough to update the graphics and changed tile descriptions. If
   --ddnet isn't specified `../ddnet` is assumed.
* easy to update tile descriptions: just edit `explain-layer/tiles.csv`
  with a text editor or libreoffice calc to modify the descriptions
  and run the script like above to update all relevant svgs
* Embedding the svg into other websites is possible with

  ```html
  <object type="image/svg+xml" data="https://ddnet.tw/docs/explain-layers/entities.svg"></object>
  ```

**Note**:
* I modified the default template to be able to put the menu into a different file. This was the best solution I found yet

### CODE REVIEW

**Comment by def-** [comment]
Should this replace the ones we have in /explain/ currently?

**Comment by Zwelf** [comment]
Yes I think it can replace the current /explain/. What are the additional steps required when replacing it?
* should the url stay the same?
* should the look of the old /explain should remain?
* check how to integrate the new svgs it into wiki.ddnet.tw (this one I wanted to do anyway)

And I forgot to add credits:
* Patiga wrote the script initially (mb. we should add an open source license to it)
* Add a CC-BY-SA 4.0 license to the explain texts
* credit timakro and Lady Saavic for the idea and initial version

**Comment by def-** [comment]
> should the url stay the same?

yes

> should the look of the old /explain should remain?

doesn't matter

**Comment by Zwelf** [comment]
I've moved the explain pages to the `/explain` directery. Only the entry point has the same url. When clicking on e.g. `Game layer` the url differs.
Another difference is that `Entity overlay` is shown by default not `Game layer`, since `Entity overlay` contains more items and players are more familiar with the entities.

I've added a license to the script after talking to @Patiga. We decided to use zlib to make a possible inclusion into the ddnet repository as unobstructed as possible.

**Comment by def-** [comment]
Thanks!

**Pull request merged**
