### PR TITLE
fix changelog li margin

### PR DESCRIPTION
**Pull request by edg-l**

### CODE REVIEW

**Comment by def-** [comment]
Any other opinions?

**Comment by Zwelf** [comment]
I think reducing the size is good, I think the current PR is cramped as well. I would suggest setting it to 0.5em after reading a bit about it\[1\]. Maybe changing `.block li` (and perhaps `.longblock li`) would be better to keep the site more consistent?

\[1\]: https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/#line-height-affects-horizontal-motion

**Comment by def-** [comment]
I'd be ok with Zwelf's suggestion. @edg-l ?

**Comment by edg-l** [comment]
done

**Pull request merged**
